### ISSUE TITLE
Build with Heroku button doesn't work

### ISSUE THREAD

**Issue by ekizean** [bih/spotify-token-swap-service#8]
It doesn't build

**Comment by david03g** [comment]
I have same problem

**Comment by ruudkalis** [comment]
The ruby gemfile requires a gem called "encrypted_strings" and clones it from github but this does repository does not exist any longer.

**Comment by ruudkalis** [comment]
The ruby gemfile requires a gem called that does not exist on github any longer:
`gem "encrypted_strings", github: "better-forks/encrypted_strings"`

There is a workaround using a cloned version of that repo called:
`gem "encrypted_strings", github: "pluginaweek/encrypted_strings"`

Create an account on Heroku and create an app. Then you open a terminal and run:
`heroku login`
This will open a browser and login to Heroku. After this clone heroku git repo:
```
heroku git:clone -a mindwalker
git add .
```
Then copy the spotify token swap service repository:
```
git clone https://github.com/bih/spotify-token-swap-service.git
cd spotify-token-swap-service/
```
Change this in Gemfile: 
`gem "encrypted_strings", github: "pluginaweek/encrypted_strings"`
And change this in Gemfile.lock:
```
GIT
  remote: git://github.com/pluginaweek/encrypted_strings.git
  revision: a9bea6b48b910e24e762662d8816709100906756
  specs:
    encrypted_strings (0.3.3)
```
And commit which will build automatically: 
```
$ git commit -am "initial commit"
$ git push heroku master
```

**Comment by StephanieSantana** [comment]
Same issue as of July 15. Will try the steps above.

_After finishing the steps above this is my new result:_ 
I am doing the following steps but am not able to finish as of the 
`git push heroku master` results in this error:

`remote:  !     No default language could be detected for this app.
remote: 			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
remote: 			See https://devcenter.heroku.com/articles/buildpacks
`

I tried adding in the buildpack but I really don't understand how it would map out for an iOS App using objective-c. Any takes on this?

**Comment by StephanieSantana** [comment]
Upon trying to understand more, I did the following:
1. I removed all objective-c code out as I may have misunderstood this.
2. I finished the gem part where I change the string, and then I directly did this `bundle install --path vendor/bundle` to update the gemlock file as this is untouchable by my machine.
3. I went back into the repository I want to finish the `git push heroku master` with and I find that even if I add in the nodeJS buildpack, do `npm init` to add in the package.json file that it prompts me  for, I still get the following:
<img width="603" alt="Screen Shot 2020-07-16 at 6 12 08 PM" src="https://user-images.githubusercontent.com/31974473/87737465-e5549d80-c78f-11ea-82b9-692f835cab93.png">

I may be misreading a step, or this solution no longer is working.

**Comment by StephanieSantana** [comment]
To circle back to this and help anyone else who was blocked like me, my colleague @timothy1ee was able to resolve this by forking this repo and applying the gem changes on the forked repo. I didn't realize that was what was asked from everyone else. Hope this unblocks anyone else who wants to use this! https://github.com/timothy1ee/spotify-token-swap-service is an example of a successful working deploy with heroku button.

**Comment by StephanieSantana** [comment]
@bih I believe this can be closed as you have fixed it. Thanks again for merging the fix!

**Comment by TheFern2** [comment]
Interesting build succeeded for me with zero changes.

**Comment by TheFern2** [comment]
> To circle back to this and help anyone else who was blocked like me, my colleague @timothy1ee was able to resolve this by forking this repo and applying the gem changes on the forked repo. I didn't realize that was what was asked from everyone else. Hope this unblocks anyone else who wants to use this! https://github.com/timothy1ee/spotify-token-swap-service is an example of a successful working deploy with heroku button.

ok nvm I am seeing crashed errors even with the timothy1ee repo 

```


2024-10-14T15:20:10.257249+00:00 app[web.1]: 	from /app/vendor/ruby-3.1.6/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'

2024-10-14T15:20:10.257249+00:00 app[web.1]: 	from /app/vendor/ruby-3.1.6/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'

2024-10-14T15:20:10.257249+00:00 app[web.1]: 	from /app/vendor/ruby-3.1.6/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'

2024-10-14T15:20:10.257250+00:00 app[web.1]: 	from /app/vendor/ruby-3.1.6/lib/ruby/gems/3.1.0/gems/bundler-2.3.27/libexec/bundle:48:in `block in <top (required)>'

2024-10-14T15:20:10.257258+00:00 app[web.1]: 	from /app/vendor/ruby-3.1.6/lib/ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'

2024-10-14T15:20:10.257258+00:00 app[web.1]: 	from /app/vendor/ruby-3.1.6/lib/ruby/gems/3.1.0/gems/bundler-2.3.27/libexec/bundle:36:in `<top (required)>'

2024-10-14T15:20:10.257258+00:00 app[web.1]: 	from /app/vendor/bundle/bin/bundle:113:in `load'

2024-10-14T15:20:10.257258+00:00 app[web.1]: 	from /app/vendor/bundle/bin/bundle:113:in `<main>'

2024-10-14T15:20:10.304103+00:00 heroku[web.1]: Process exited with status 1

2024-10-14T15:20:10.325821+00:00 heroku[web.1]: State changed from starting to crashed


```
